---
name: xcop
on:
  push:
  pull_request:
jobs:
  xcop:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: g4s8/xcop-action@master
